try {
	dosomething()
catch (e)
	log("something went wrong")
}
